# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 13:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('culturals', '0002_auto_20160830_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultural',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 9, 13, 44, 47, 928947, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
