# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 17:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=120)),
                ('pic', models.ImageField(upload_to='movies/')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('RUN', 'Running')], default='NEW', max_length=3)),
                ('language', models.CharField(choices=[('ENG', 'English'), ('MAL', 'Malayalam'), ('TML', 'Tamil'), ('HID', 'Hindi')], default='ENG', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_slug', models.SlugField()),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='theatre/')),
                ('landmark', models.CharField(default=None, max_length=100)),
                ('location', geoposition.fields.GeopositionField(max_length=42)),
                ('contact_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Format: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('online_reservation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('link_to_reservation_site', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('Morning', (('9', '09:00 am'), ('9:15', '09:15 am'), ('9:30', '09:30 am'), ('9:45', '09:45 am'), ('10', '10:00 am'), ('10:15', '10:15 am'), ('10:30', '10:30 am'), ('10:45', '10:45 am'), ('11', '11:00 am'), ('10:15', '10:15 am'), ('11:30', '11:30 am'), ('11:45', '11:45 am'))), ('Noon', (('12', '12:00 pm'), ('12:15', '12:15 pm'), ('12:30', '12:30 pm'), ('12:45', '12:45 pm'), ('1', '01:00 pm'), ('1:15', '01:15 pm'), ('1:30', '01:30 pm'), ('1:45', '01:45 pm'), ('2', '02:00 pm'), ('2:15', '02:15 pm'), ('2:30', '02:30 pm'), ('2:45', '02:45 pm'), ('3', '03:00 pm'), ('3:15', '03:15 pm'), ('3:30', '03:30 pm'), ('3:45', '03:45 pm'))), ('Evening', (('4', '04:00 pm'), ('4:15', '04:15 pm'), ('4:30', '04:30 pm'), ('4:45', '04:45 pm'), ('5', '05:00 pm'), ('5:15', '01:15 pm'), ('5:30', '05:30 pm'), ('5:45', '05:45 pm'), ('6', '06:00 pm'), ('6:15', '06:15 pm'), ('6:30', '06:30 pm'), ('6:45', '06:45 pm'), ('7', '07:00 pm'), ('7:15', '07:15 pm'), ('7:30', '07:30 pm'), ('7:45', '07:45 pm'))), ('Night', (('8', '08:00 pm'), ('8:15', '08:15 pm'), ('8:30', '08:30 pm'), ('8:45', '08:45 pm'), ('9', '09:00 pm'), ('9:15', '09:15 pm'), ('9:30', '09:30 pm'), ('9:45', '09:45 pm'), ('10', '10:00 pm'), ('10:15', '10:15 pm'), ('10:30', '10:30 pm'), ('10:45', '10:45 pm'), ('11', '11:00 pm'), ('11:15', '11:15 pm'), ('11:30', '11:30 pm'), ('11:45', '11:45 pm')))], max_length=100)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time', to='movies.Show')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Theatre'),
        ),
        migrations.AddField(
            model_name='hall',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hall', to='movies.Theatre'),
        ),
        migrations.AlterUniqueTogether(
            name='show',
            unique_together=set([('movie', 'theatre', 'hall')]),
        ),
    ]
